### PR TITLE
Implement macro to render a markdown file from github on Confluence

### PR DESCRIPTION
**Pull request by slide**
This creates a github-markdown-content macro that will render a markdown file from github on Confluence. This will allow plugin owners to manage their wiki page via github. This could also be used to render a markdown changelog on the wiki as well.

### CODE REVIEW

**Comment by slide** [comment]
I think this is a stupid line ending problem...Windows vs. Linux. I'll run on my Linux box to verify.

**Comment by rtyler** [comment]
@slide unauthenticated calls to GitHub get rate-limited pretty hard. What kind of caching is here? I didn't see anything directly on the request path in the first files I looked at :/

**Comment by slide** [comment]
@rtyler, very valid concern. There is currently no caching, I will look into that.

**Comment by rtyler** [comment]
@slide we do have an nginx cache in front of Confluence which means every request isn't necessarily served by confluence.

I wonder if GitHub rate limits HEAD requests, allowing you to make each page load see if the content is changed and if-so request, otherwise cache

**Comment by slide** [comment]
Is this in use on Jenkins' Confluence?  https://github.com/kohsuke/confluence-static-cache

**Comment by slide** [comment]
I wrote a little test that did 1000 HEAD requests against a resource on raw.githubusercontent.com and it returned a success code for all 1000. I'm not really willing to trust this that much though. I wonder if it would be possible to create a token for a user with no access to anything for purposes like this.

**Comment by daniel-beck** [comment]
This should probably be done as an improvement to the plugin site instead, like, when it's a wiki URL today, it scrapes it. Anyone opposed to closing this?

**Pull request closed without merging**
